---

- name: "Apache installation"
  hosts: prod
  become: true
  vars:
    - ansible_sudo_pass: admin
  pre_tasks:
   - name: "Install EPEL repo"
     yum:
      name: epel-release
      state: present
   - name: "Install python-pip"
     yum:
      name: python2-pip.noarch
      state: present
      update_cache: yes
   - name: "Install docker-python"
     pip:
      name: docker-py
  tasks:
   - name: "Create Apache container"
     docker_container:
       name: webapp
       image: httpd
       ports: 80:80
